### ISSUE TITLE
Cannot Found new Controller for second theme

### ISSUE THREAD

**Issue by irfnrdh** [3x1io/filament-themes#1]
I have create other theme 
but `Target class [Themes\second\controllers\HomeController] does not exist`

route 
```
Route::middleware(['web'])->group(static function () {
    Route::namespace(theme_namespace())->name('theme/')->group(static function () {
        Route::get('/','HomeController@index')->name('index');
    });
});
```

**Comment by fadymondy** [comment]
try to add this to your composer.json

```json
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Themes\\": "resources/views/themes/"
        }
    },
```

**Comment by fadymondy** [comment]
i add this to the docs, thanks

**Comment by irfnrdh** [comment]
Thanks that problem solve, but every time I add new route that always call "php artisan optimize" how to make it works auto without command ^_^ oh ya, how to costume group page `$navigationGroup`, Thanks @3x1io
