### ISSUE TITLE
Error: Spatie  \  LaravelSettings  \  Exceptions  \  MissingSettings

### ISSUE THREAD

**Issue by Odilbukh** [3x1io/filament-themes#10]
Message: Tried loading settings 'io3x1\FilamentThemes\Settings\ThemesSettings', and following properties were missing: theme_name, theme_path, theme_namespace, theme_main_color, theme_secandry_color, theme_sub_color, theme_css, theme_js, theme_header,

Path: http://127.0.0.1:8000/admin/themes

View: resources/views/filament/pages/themes.blade.php

![image](https://user-images.githubusercontent.com/22895615/209469280-d4ae68d5-8b91-4f06-a89b-147d9092668e.png)

**Comment by Odilbukh** [comment]
I just installed the package in a fresh project. I have done everything from documentation while installing. It was installed good. "Themes" appeared in navbar. But when I click  to the button there is the error like above 

Hope You will help ASAP to fix the issue

Thanks!

**Comment by Odilbukh** [comment]
Helper
![image](https://user-images.githubusercontent.com/22895615/209471434-1b65fb8e-8d30-4e85-b8b4-211aa3c9db33.png)

**Comment by Odilbukh** [comment]
Also I have installed 3x1io/filament-sitemap but in function setting('$key') there are keys only from Theme not Sitemap

**Comment by fadymondy** [comment]
i will fix it on the next version with tons of new features.

**Comment by fadymondy** [comment]
it's done now please update.
