### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by erenergul** [3x1io/filament-themes#3]
Warning: Ambiguous class resolution, "Themes\main\controllers\HomeController" was found 2x: in "/Users/..../www/filament/resources/views/themes/main/controllers/HomeController.php" and "/Users/..../www/filament/vendor/3x1io/filament-themes/resources/views/themes/main/controllers/HomeController.php", the first will be used.

Hi , Whats the reason behind it ? Its working but i can't use theme vendor controller. Should i change my controller name ? If it is not break anything , Thats fine but want to know whats going on behind scenes.

**Comment by fadymondy** [comment]
I will fix it and build a command to generate a new theme, so the package will start with empty themes and you can add a new theme by this command

```bash
php artisan filament-themes:generate
```

**Comment by fadymondy** [comment]
it's done now you can check it.
