### ISSUE TITLE
On preview not getting added changes

### ISSUE THREAD

**Issue by dev-archana-soni** [3x1io/filament-themes#5]
Hi,

I have installed this plugin and getting one theme which name was likee main. Then have created one more theme inside that same like main just name is est and changed few css. But i can not see in preview of test just redirect ro dashboard. Why? and Can you please guide me like how can check ?

This plugin is same is worked like same wordpress theme right? like multiple themes can add and can change each theme view.

Here i am going to attached screnn shot so please check it and help on it.

Thank you in advance

![image](https://user-images.githubusercontent.com/94445886/174721817-ae23e3b6-23d6-400f-9487-b21f5cf9a548.png)

![image](https://user-images.githubusercontent.com/94445886/174722175-fc933a93-513b-427b-bd60-f98abdfcd93b.png)

**Comment by fadymondy** [comment]
yes it's working like wordpress, i think your problem is route/cache

try to use this command

```bash
php artisan route:clear
```

and remove the main route from `routes/web.php` because it's override the theme package routes

**Comment by fadymondy** [comment]
it's done now you can check it.
