### ISSUE TITLE
Missing policy for view_themes

### ISSUE THREAD

**Issue by howdu** [3x1io/filament-themes#8]
`auth()->user()->can('view_themes')` is always turning false.

**Comment by shankhadevpadam** [comment]
One quick solution is to define a gate inside AuthServiceProvider.php

```php
 Gate::define('view_themes', function (\App\Models\User $user) {
      return $user->isAdmin();
  });
```

**Comment by howdu** [comment]
Thanks we went with a different solution so unable to test that now.
