### ISSUE TITLE
You broke my entire website. 

### ISSUE THREAD

**Issue by erenergul** [3x1io/filament-themes#9]
if (!function_exists('setting')) {
    function setting($key)
    {
        $setting = SettingsProperty::where('name', $key)->first();
        if ($setting) {
            return json_decode($setting->payload);
        } else {
            return false;
        }
    }
}

I was using setting() helper all around my frontend. When i update it. It takes me few days to understand whats wrong. Why did you do that ? I create custom helper but you should warn people for break changes.

**Comment by fadymondy** [comment]
Prevent repeated queries for individual setting values. by @shankhadevpadam shankha
